package com.example.feedbox;

public class URLDatabase
{
    static String URLLH = "http://192.168.1.11/feedbox/";
    public static String URL_BAR_GRAPH = URLLH + "URL_BAR_GRAPH.php";
    public static String URL_AY_ACTIVE = URLLH + "URL_AY_ACTIVE.php";
    public static String URL_AY_ADD = URLLH + "URL_AY_ADD.php";
    public static String URL_AY_EDIT = URLLH + "URL_AY_EDIT.php";
    public static String URL_AY_DELETE = URLLH + "URL_AY_DELETE.php";
    public static String URL_AY_LIST = URLLH + "URL_AY_LIST.php";
    public static String URL_LIST_SPECIFIC = URLLH + "URL_LIST_SPECIFIC.php";
    public static String URL_LIST_SPECIFIC_ADD = URLLH + "URL_LIST_SPECIFIC_ADD.php";
    public static String URL_LIST_SPECIFIC_EDIT = URLLH + "URL_LIST_SPECIFIC_EDIT.php";
    public static String URL_LIST_SPECIFIC_DELETE = URLLH + "URL_LIST_SPECIFIC_DELETE.php";
    public static String URL_MUTE_USER = URLLH + "URL_MUTE_USER.php";
    public static String URL_MUTE_CHECK_USER = URLLH + "URL_MUTE_CHECK_USER.php";
    public static String URL_CHECK_ACCOUNT = URLLH + "URL_CHECK_ACCOUNT.php";
    public static String URL_SEND_CODE = URLLH + "URL_SEND_CODE.php";
    public static String URL_REGISTER = URLLH + "URL_REGISTER.php";
    public static String URL_LOGIN = URLLH + "URL_LOGIN.php";
    public static String URL_LOGIN_ADMIN = URLLH + "URL_LOGIN_ADMIN.php";
    public static String URL_HOME = URLLH + "URL_HOME.php";
    public static String URL_NEW_PASSWORD = URLLH + "URL_NEW_PASSWORD.php";
    public static String URL_ACCOUNT_PICTURE_UPDATE = URLLH + "URL_ACCOUNT_PICTURE_UPDATE.php";
    public static String URL_ACCOUNT_SETTING_UPDATE = URLLH + "URL_ACCOUNT_SETTING_UPDATE.php";
    public static String URL_ADMIN_LIST = URLLH + "URL_ADMIN_LIST.php";
    public static String URL_ADMIN_ADD = URLLH + "URL_ADMIN_ADD.php";
    public static String URL_ADMIN_EDIT = URLLH + "URL_ADMIN_EDIT.php";
    public static String URL_CATEGORY_LIST = URLLH + "URL_CATEGORY_LIST.php";
    public static String URL_CATEGORY_ADD = URLLH + "URL_CATEGORY_ADD.php";
    public static String URL_CATEGORY_EDIT = URLLH + "URL_CATEGORY_EDIT.php";
    public static String URL_CATEGORY_DELETE = URLLH + "URL_CATEGORY_DELETE.php";
    public static String URL_SUB_CATEGORY_LIST = URLLH + "URL_SUB_CATEGORY_LIST.php";
    public static String URL_SUB_CATEGORY_ADD = URLLH + "URL_SUB_CATEGORY_ADD.php";
    public static String URL_SUB_CATEGORY_EDIT = URLLH + "URL_SUB_CATEGORY_EDIT.php";
    public static String URL_SUB_CATEGORY_DELETE = URLLH + "RL_SUB_CATEGORY_DELETE.php";
    public static String URL_SUB_CATEGORY_NAME_LIST = URLLH + "URL_SUB_CATEGORY_NAME_LIST.php";
    public static String URL_SEND_FEEDBACK = URLLH + "URL_SEND_FEEDBACK.php";
    public static String URL_FEEDBACK_ADMIN_LIST = URLLH + "URL_FEEDBACK_ADMIN_LIST.php";
    public static String URL_FEEDBACK_LIST = URLLH + "URL_FEEDBACK_LIST.php";
    public static String URL_FEEDBACK_LIST_STATUS = URLLH + "URL_FEEDBACK_LIST_STATUS.php";
    public static String URL_FEEDBACK_LIST_UPDATE = URLLH + "URL_FEEDBACK_LIST_UPDATE.php";
    public static String URL_MONTHLY_SALES = URLLH + "RL_MONTHLY_SALES.php";
    public static String URL_PIE_CHART_FEEDBACK = URLLH + "URL_PIE_CHART_FEEDBACK.php";
    public static String URL_USER_LIST = URLLH + "URL_USER_LIST.php";
    public static String URL_USER_TYPE_LIST = URLLH + "URL_USER_TYPE_LIST.php";
    public static String URL_USER_STATUS_EDIT = URLLH + "URL_USER_STATUS_EDIT.php";
    public static String URL_SENTIMENT_LIST = URLLH + "URL_SENTIMENT_LIST.php";
    public static String URL_SEND_FEEDBACK_EMAIL = URLLH + "URL_SEND_FEEDBACK_EMAIL.php";
    public static String URL_FEEDBACK_COMPLETE = URLLH + "URL_FEEDBACK_COMPLETE.php";
}
