package com.example.feedbox;

public class URLDatabase
{
//        static String LINK_PHP = "http://192.168.1.13/feedbox/";
//    static String LINK_PHP = "http://feedbox.000.pe/";
    public static String LINK_PHP = "https://dysphoric-rheostat.000webhostapp.com/";
    public static String URL_REPORT = LINK_PHP + "URL_REPORT.php";
    public static String URL_BAR_GRAPH = LINK_PHP + "URL_BAR_GRAPH.php";
    public static String URL_AY_ACTIVE = LINK_PHP + "URL_AY_ACTIVE.php";
    public static String URL_AY_ADD = LINK_PHP + "URL_AY_ADD.php";
    public static String URL_AY_EDIT = LINK_PHP + "URL_AY_EDIT.php";
    public static String URL_AY_DELETE = LINK_PHP + "URL_AY_DELETE.php";
    public static String URL_AY_LIST = LINK_PHP + "URL_AY_LIST.php";
    public static String URL_LIST_SPECIFIC = LINK_PHP + "URL_LIST_SPECIFIC.php";
    public static String URL_LIST_SPECIFIC_ADD = LINK_PHP + "URL_LIST_SPECIFIC_ADD.php";
    public static String URL_LIST_SPECIFIC_EDIT = LINK_PHP + "URL_LIST_SPECIFIC_EDIT.php";
    public static String URL_LIST_SPECIFIC_DELETE = LINK_PHP + "URL_LIST_SPECIFIC_DELETE.php";
    public static String URL_MUTE_USER = LINK_PHP + "URL_MUTE_USER.php";
    public static String URL_MUTE_CHECK_USER = LINK_PHP + "URL_MUTE_CHECK_USER.php";
    public static String URL_CHECK_ACCOUNT = LINK_PHP + "URL_CHECK_ACCOUNT.php";
    public static String URL_SEND_CODE = LINK_PHP + "URL_SEND_CODE.php";
    public static String URL_REGISTER = LINK_PHP + "URL_REGISTER.php";
    public static String URL_LOGIN = LINK_PHP + "URL_LOGIN.php";
    public static String URL_LOGIN_ADMIN = LINK_PHP + "URL_LOGIN_ADMIN.php";
    public static String URL_HOME = LINK_PHP + "URL_HOME.php";
    public static String URL_NEW_PASSWORD = LINK_PHP + "URL_NEW_PASSWORD.php";
    public static String URL_ACCOUNT_PICTURE_UPDATE = LINK_PHP + "URL_ACCOUNT_PICTURE_UPDATE.php";
    public static String URL_ACCOUNT_SETTING_UPDATE = LINK_PHP + "URL_ACCOUNT_SETTING_UPDATE.php";
    public static String URL_ADMIN_LIST = LINK_PHP + "URL_ADMIN_LIST.php";
    public static String URL_ADMIN_ADD = LINK_PHP + "URL_ADMIN_ADD.php";
    public static String URL_ADMIN_EDIT = LINK_PHP + "URL_ADMIN_EDIT.php";
    public static String URL_CATEGORY_LIST = LINK_PHP + "URL_CATEGORY_LIST.php";
    public static String URL_CATEGORY_SUB_LIST = LINK_PHP + "URL_CATEGORY_SUB_LIST.php";
    public static String URL_CATEGORY_ADD = LINK_PHP + "URL_CATEGORY_ADD.php";
    public static String URL_CATEGORY_EDIT = LINK_PHP + "URL_CATEGORY_EDIT.php";
    public static String URL_CATEGORY_DELETE = LINK_PHP + "URL_CATEGORY_DELETE.php";
    public static String URL_SUB_CATEGORY_LIST = LINK_PHP + "URL_SUB_CATEGORY_LIST.php";
    public static String URL_SUB_CATEGORY_ADD = LINK_PHP + "URL_SUB_CATEGORY_ADD.php";
    public static String URL_SUB_CATEGORY_EDIT = LINK_PHP + "URL_SUB_CATEGORY_EDIT.php";
    public static String URL_SUB_CATEGORY_DELETE = LINK_PHP + "RL_SUB_CATEGORY_DELETE.php";
    public static String URL_SUB_CATEGORY_NAME_LIST = LINK_PHP + "URL_SUB_CATEGORY_NAME_LIST.php";
    public static String URL_SEND_FEEDBACK = LINK_PHP + "URL_SEND_FEEDBACK.php";
    public static String URL_FEEDBACK_ADMIN_LIST = LINK_PHP + "URL_FEEDBACK_ADMIN_LIST.php";
    public static String URL_FEEDBACK_LIST = LINK_PHP + "URL_FEEDBACK_LIST.php";
    public static String URL_FEEDBACK_LIST_STATUS = LINK_PHP + "URL_FEEDBACK_LIST_STATUS.php";
    public static String URL_FEEDBACK_LIST_UPDATE = LINK_PHP + "URL_FEEDBACK_LIST_UPDATE.php";
    public static String URL_MONTHLY_SALES = LINK_PHP + "RL_MONTHLY_SALES.php";
    public static String URL_PIE_CHART_FEEDBACK = LINK_PHP + "URL_PIE_CHART_FEEDBACK.php";
    public static String URL_PIE_SUB_CHART_FEEDBACK = LINK_PHP + "URL_PIE_SUB_CHART_FEEDBACK.php";
    public static String URL_USER_LIST = LINK_PHP + "URL_USER_LIST.php";
    public static String URL_USER_TYPE_LIST = LINK_PHP + "URL_USER_TYPE_LIST.php";
    public static String URL_USER_STATUS_EDIT = LINK_PHP + "URL_USER_STATUS_EDIT.php";
    public static String URL_SENTIMENT_LIST = LINK_PHP + "URL_SENTIMENT_LIST.php";
    public static String URL_SEND_FEEDBACK_EMAIL = LINK_PHP + "URL_SEND_FEEDBACK_EMAIL.php";
    public static String URL_FEEDBACK_COMPLETE = LINK_PHP + "URL_FEEDBACK_COMPLETE.php";
}
